--VAMOS A RECONFIGURAR EL ARCHIVO DE CONFIGURACIÓN PARA QUE NOS PERMITA LA CARACTER
USE MASTER
GO

--AÚN NO SE ACTIVAN LAS OPCIONES AVANZADAS
EXEC SP_CONFIGURE 'show advanced options', 1
GO

--ACTUALIZAMOS EL VALOR
RECONFIGURE
GO

--ACTIVAMOS LA CARACTERÍSTICA
EXEC SP_CONFIGURE 'contained database authentication', 1
GO

--actualizamos de nuevo
RECONFIGURE
GO

----
---HASTA AQUÍ PREPARAMOS EL ENTORNO PARA LO QUE VAMOS A EJECUTAR
---

DROP DATABASE IF EXISTS Salvamento_Contenida
GO

CREATE DATABASE Salvamento_Contenida
CONTAINMENT=PARTIAL --ESTO ES LO QUE INDICA QUE ES CONTENIDA
GO


--UNA VEZ CREADA LA ACTIVAMOS 
USE Salvamento_Contenida
GO

--CREAMOS UN USUARIO
DROP USER IF EXISTS jason
GO
CREATE USER jason
	WITH PASSWORD = 'abcd1234.',
	DEFAULT_SCHEMA=dbo
GO 

--en desuso
--exec sp_addrolemember 'db_owner', 'jason'
--GO
--formato nuevo, es el que usaremos
ALTER ROLE db_owner
ADD MEMBER jason

--DAMOS PERMISO A JASON PARA QUE SE PUEDA CONECTAR, PORQUE LO HEMOS CREADO EN UNA BD CONTENIDA
GRANT CONNECT TO jason
GO